larson:
  host: "172.17.20.37"
  user: "OWLDataWarehouse"
  password: "![wLTOf7RDepaYEqIqxpL8/w==]"
  account_name: "pi75377.central-us.azure"
  warehouse: "DEV_INGESTION_WH"
  database: "LARSON_DEV"
  schema1: "BKL_STAGE"
  schema2: "NMA_STAGE"
  schema3: "OEI_STAGE"
  schema4: "LARSON_STAGE"
  snowflake_username: "HARIVAMSI_PULLIPUDI"
  snowflake_password: "![57BoO29DSgKUhmlQ6SxR8w==]"
  role: "DEV_INGESTION_ROLE"

cron:
  Expression: "0 0 1 1/1 * ? *"
  Expression_financial_day: "0 0 1 1/1 * ? *"
  Expression_financial_week: "0 0 1 1/7 * ? *"
  Expression_financial_week_delay: "0 0 2 1/7 * ? *"
  Expression_sales_day: "0 30 2 1/1 * ? *"
  Expression_sales_week: "0 30 2 1/7 * ? *"
  Expression_sales_day_delay: "0 30 3 1/7 * ? *"
  Expression_sales_week_delay: "0 30 3 1/7 * ? *"
  Expression_inventory_day: "0 0 4 1/1 * ? *"
  Expression_inventory_week: "0 0 4 1/7 * ? *"
  Expression_inventory_day_delay: "0 30 3 1/7 * ? *"
  Expression_inventory_week_delay: "0 30 3 1/7 * ? *"
  TimeZone: "GMT-4"
