larson:
  host: "172.17.20.37"
  user: "OWLDataWarehouse"
  password: "![wLTOf7RDepaYEqIqxpL8/w==]"
  account_name: "pi75377.central-us.azure"
  warehouse: "DEV_INGESTION_WH"
  database: "LARSON_DEV"
  schema1: "BKL_STAGE"
  schema2: "NMA_STAGE"
  schema3: "OEI_STAGE"
  schema4: "LARSON_STAGE"
  snowflake_username: "HARIVAMSI_PULLIPUDI"
  snowflake_password: "![57BoO29DSgKUhmlQ6SxR8w==]"
  role: "DEV_INGESTION_ROLE"

crompco:
  url: "jdbc:pervasive://172.16.1.36:1583/CROMPCOLLC"
  driver: "com.pervasive.jdbc.v2.Driver"
  user: "Peachtree"
  password: "![w9GhxeQ4iSU=]"
  account: "pi75377.central-us.azure"
  warehouse: "DEV_INGESTION_WH"
  database: "CROMPCO_DEV"
  schema: "CROMPCO_STAGE"
  snowflake_username: "HARIVAMSI_PULLIPUDI"
  snowflake_password: "![GO0BX/UmhVXmGpCWkTYnQA==]"
  role: "DEV_INGESTION_ROLE"

crompco_sales:
  host: "vault-service.crquhfau4stz.us-east-1.rds.amazonaws.com"
  user: "owl_datawarehouse"
  password: "![THTMSzJsZr48Cu0gek5rYmtBhIW7ugcu]"
  account: "pi75377.central-us.azure"
  warehouse: "DEV_INGESTION_WH"
  database: "CROMPCO_DEV"
  schema: "CROMPCO_STAGE"
  snowflake_username: "HARIVAMSI_PULLIPUDI"
  snowflake_password: "![GO0BX/UmhVXmGpCWkTYnQA==]"
  role: "DEV_INGESTION_ROLE"
  

cron:
  Expression: "0 0 1 1/1 * ? *"
  Expression_Financial_day: "0 0 1 1/1 * ? *"
  Expression_Financial_week: "0 0 1 1/7 * ? *"
  Expression_Financial_week_delay: "0 0 2 1/7 * ? *"
  Expression_sales_day: "0 30 2 1/1 * ? *"
  Expression_sales_week: "0 30 2 1/7 * ? *"
  Expression_Sales_day_delay: "0 30 3 1/7 * ? *"
  Expression_Sales_week_delay: "0 30 3 1/7 * ? *"
  Expression_inventory_day: "0 0 4 1/1 * ? *"
  Expression_inventory_week: "0 0 4 1/7 * ? *"
  Expression_inventory_day_delay: "0 30 3 1/7 * ? *"
  Expression_inventory_week_delay: "0 30 3 1/7 * ? *"
  TimeZone: "GMT-4"
