TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTFIN_NMA_GL20000 ;
INSERT INTO LARSON_DEV.NMA_RAW.RTFIN_NMA_GL20000 select * from LARSON_DEV.NMA_STAGE.STGFIN_NMA_GL20000 ;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGFIN_NMA_GL20000 ;