TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTFIN_NMASY40100;
INSERT INTO LARSON_DEV.NMA_RAW.RTFIN_NMASY40100 select * from LARSON_DEV.NMA_STAGE.STGFIN_NMA_SY40100;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGFIN_NMA_SY40100;