TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTFIN_NMA_GL00100 ;
INSERT INTO LARSON_DEV.NMA_RAW.RTFIN_NMA_GL00100 select * from LARSON_DEV.NMA_STAGE.STGFIN_NMA_GL00100 ;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGFIN_NMA_GL00100 ;