TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTFIN_NMAGL00105;
INSERT INTO LARSON_DEV.NMA_RAW.RTFIN_NMAGL00105 select * from LARSON_DEV.NMA_STAGE.STGFIN_NMA_GL00105;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGFIN_NMA_GL00105;