TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTFIN_NMA_GL30000 ;
INSERT INTO LARSON_DEV.NMA_RAW.RTFIN_NMA_GL30000 select * from LARSON_DEV.NMA_STAGE.STGFIN_NMA_GL30000 ;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGFIN_NMA_GL30000 ;