TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTFIN_LARSON_gl20000 ;
INSERT INTO LARSON_DEV.LARSON_RAW.RTFIN_LARSON_gl20000 SELECT * FROM LARSON_DEV.LARSON_STAGE.STGFIN_LARSON_gl20000 ;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGFIN_LARSON_gl20000 ;