truncate table LARSON_DEV.BKL_RAW.RTFIN_BKLGL11110;

insert into LARSON_DEV.BKL_RAW.RTFIN_BKLGL11110 select * from LARSON_DEV.BKL_STAGE.STGFIN_BKLGL11110;

truncate table LARSON_DEV.BKL_STAGE.STGFIN_BKLGL11110;