TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTFIN_LARSONGL00100 ;
INSERT INTO LARSON_DEV.LARSON_RAW.RTFIN_LARSONGL00100 select * from LARSON_DEV.LARSON_STAGE.STGFIN_LARSONGL00100 ;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGFIN_LARSONGL00100 ;