truncate table LARSON_DEV.NMA_RAW.RTFIN_NMAGL11111;

insert into LARSON_DEV.NMA_RAW.RTFIN_NMAGL11111 select * from LARSON_DEV.NMA_STAGE.STGFIN_NMAGL11111;

truncate table LARSON_DEV.NMA_STAGE.STGFIN_NMAGL11111;
