truncate table LARSON_DEV.BKL_RAW.RTFIN_BKLGL00105;

insert into LARSON_DEV.BKL_RAW.RTFIN_BKLGL00105 select * from LARSON_DEV.BKL_STAGE.STGFIN_BKLGL00105;

truncate table LARSON_DEV.BKL_STAGE.STGFIN_BKLGL00105;
