truncate table LARSON_DEV.BKL_RAW.RTFIN_BKLGL00201;

insert into LARSON_DEV.BKL_RAW.RTFIN_BKLGL00201 select * from LARSON_DEV.BKL_STAGE.STGFIN_BKLGL00201;

truncate table LARSON_DEV.BKL_STAGE.STGFIN_BKLGL00201;