truncate table LARSON_DEV.BKL_RAW.RTFIN_BKLGL11111;

insert into LARSON_DEV.BKL_RAW.RTFIN_BKLGL11111 select * from LARSON_DEV.BKL_STAGE.STGFIN_BKLGL11111;

truncate table LARSON_DEV.BKL_STAGE.STGFIN_BKLGL11111;
