truncate table LARSON_DEV.OEI_RAW.RTFIN_OEIGL00105;

insert into LARSON_DEV.OEI_RAW.RTFIN_OEIGL00105 select * from LARSON_DEV.OEI_STAGE.STGFIN_OEI_GL00105;

truncate table LARSON_DEV.OEI_STAGE.STGFIN_OEI_GL00105;