truncate table LARSON_DEV.BKL_RAW.RTFIN_BKLSY40100;

insert into LARSON_DEV.BKL_RAW.RTFIN_BKLSY40100 select * from LARSON_DEV.BKL_STAGE.STGFIN_BKLSY40100;

truncate table LARSON_DEV.BKL_STAGE.STGFIN_BKLSY40100;
