TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTFIN_LARSONGL00105;
INSERT INTO LARSON_DEV.LARSON_RAW.RTFIN_LARSONGL00105 select * from LARSON_DEV.LARSON_STAGE.STGFIN_LARSON_GL00105;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGFIN_LARSON_GL00105;