truncate table LARSON_DEV.LARSON_RAW.RTFIN_LARSONGL00201;

insert into LARSON_DEV.LARSON_RAW.RTFIN_LARSONGL00201 select * from LARSON_DEV.LARSON_STAGE.STGFIN_LARSONGL00201;

truncate table LARSON_DEV.LARSON_STAGE.STGFIN_LARSONGL00201;