truncate table LARSON_DEV.NMA_RAW.RTFIN_NMAGL11110;

insert into LARSON_DEV.NMA_RAW.RTFIN_NMAGL11110 select * from LARSON_DEV.NMA_STAGE.STGFIN_NMAGL11110;

truncate table LARSON_DEV.NMA_STAGE.STGFIN_NMAGL11110;
