truncate table LARSON_DEV.LARSON_RAW.RTFIN_LARSONGL11110;

insert into LARSON_DEV.LARSON_RAW.RTFIN_LARSONGL11110 select * from LARSON_DEV.LARSON_STAGE.STGFIN_LARSONGL11110;

truncate table LARSON_DEV.LARSON_STAGE.STGFIN_LARSONGL11110;
