truncate table LARSON_DEV.OEI_RAW.RTFIN_OEIGL11110;

insert into LARSON_DEV.OEI_RAW.RTFIN_OEIGL11110 select * from LARSON_DEV.OEI_STAGE.STGFIN_OEIGL11110;

truncate table LARSON_DEV.OEI_STAGE.STGFIN_OEIGL11110;
