TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTFIN_LARSONSY40100;
INSERT INTO LARSON_DEV.LARSON_RAW.RTFIN_LARSONSY40100 select * from LARSON_DEV.LARSON_STAGE.STGFIN_LARSON_SY40100;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGFIN_LARSON_SY40100;