truncate table LARSON_DEV.OEI_RAW.RTFIN_OEIGL11111;

insert into LARSON_DEV.OEI_RAW.RTFIN_OEIGL11111 select * from LARSON_DEV.OEI_STAGE.STGFIN_OEIGL11111;

truncate table LARSON_DEV.OEI_STAGE.STGFIN_OEIGL11111;
