truncate table LARSON_DEV.BKL_RAW.RTFIN_BKLGL00100;

insert into LARSON_DEV.BKL_RAW.RTFIN_BKLGL00100 select * from LARSON_DEV.BKL_STAGE.STGFIN_BKLGL00100;

truncate table LARSON_DEV.BKL_STAGE.STGFIN_BKLGL00100;
