truncate table LARSON_DEV.OEI_RAW.RTFIN_OEIGL00100;

insert into LARSON_DEV.OEI_RAW.RTFIN_OEIGL00100 select * from LARSON_DEV.OEI_STAGE.STGFIN_OEI_GL00100;

truncate table LARSON_DEV.OEI_STAGE.STGFIN_OEI_GL00100;