truncate table LARSON_DEV.NMA_RAW.RTFIN_NMAGL00201;

insert into LARSON_DEV.NMA_RAW.RTFIN_NMAGL00201 select * from LARSON_DEV.NMA_STAGE.STGFIN_NMAGL00201;

truncate table LARSON_DEV.NMA_STAGE.STGFIN_NMAGL00201;