TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOAPOBL ;
INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOAPOBL SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOAPOBL ;
TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOAPOBL ;
