TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTSAL_LARSON_JC20504 ;
INSERT INTO LARSON_DEV.LARSON_RAW.RTSAL_LARSON_JC20504 SELECT * FROM LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_JC20504 ;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_JC20504 ;