TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMTYPE;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMTYPE SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMTYPE;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMTYPE;