TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTSAL_LARSON_SV00701 ;
INSERT INTO LARSON_DEV.LARSON_RAW.RTSAL_LARSON_SV00701 SELECT * FROM LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_SV00701 ;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_SV00701 ;