DELETE FROM WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOGLPOST
WHERE FISCALYR = (DATE_PART(YEAR,CURRENT_DATE())-1)::STRING or
      FISCALYR =  DATE_PART(YEAR,CURRENT_DATE())::STRING;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOGLPOST SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOGLPOST;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOGLPOST;