TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_JC20511;
INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_JC20511 SELECT * FROM LARSON_DEV.NMA_STAGE.STGSAL_NMA_JC20511;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_JC20511;
