TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOAROBL ;
INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOAROBL SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOAROBL ;
TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOAROBL ;
