TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_RM00301 ;
INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_RM00301 SELECT * FROM LARSON_DEV.NMA_STAGE.STGSAL_NMA_RM00301 ;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_RM00301 ;