DELETE FROM WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMPH
WHERE TXFISCALYR = (DATE_PART(YEAR,CURRENT_DATE())-1)::STRING or
      TXFISCALYR =  DATE_PART(YEAR,CURRENT_DATE())::STRING;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMPH SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMPH;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMPH;