TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOARTCR;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOARTCR SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOARTCR;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOARTCR;