TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_JC40303 ;
INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_JC40303 SELECT * FROM LARSON_DEV.NMA_STAGE.STGSAL_NMA_JC40303 ;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_JC40303 ;