TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_GL20000 ;

INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_GL20000 select * from LARSON_DEV.NMA_STAGE.STGSAL_NMA_GL20000 ;

TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_GL20000 ;