TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_GL30000 ;
INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_GL30000 select * from LARSON_DEV.NMA_STAGE.STGSAL_NMA_GL30000 ;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_GL30000 ;