TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMDTPH ;
INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMDTPH SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMDTPH ;
TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMDTPH ;