TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOARRFH;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOARRFH SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOARRFH;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOARRFH;