TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_zzz57Periods;

INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_zzz57Periods SELECT * FROM LARSON_DEV.NMA_STAGE.STGSAL_NMA_zzz57Periods;

TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_zzz57Periods;