TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_JC30501;
INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_JC30501 SELECT * FROM LARSON_DEV.NMA_STAGE.STGSAL_NMA_JC30501;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_JC30501;