TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTSAL_LARSON_SV00564 ;
INSERT INTO LARSON_DEV.LARSON_RAW.RTSAL_LARSON_SV00564 SELECT * FROM LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_SV00564 ;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_SV00564 ;