TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOAPTCR;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOAPTCR SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOAPTCR;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOAPTCR ​;