DELETE FROM WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOGLJED 
WHERE substring(cast(RATEDATE as varchar),1,4) = (DATE_PART(YEAR,CURRENT_DATE())-1)::STRING or
      substring(cast(RATEDATE as varchar),1,4) =  DATE_PART(YEAR,CURRENT_DATE())::STRING;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOGLJED SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOGLJED;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOGLJED;