TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_JC01701 ;
INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_JC01701 SELECT * FROM LARSON_DEV.NMA_STAGE.STGSAL_NMA_JC01701 ;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_JC01701 ;