TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTSAL_LARSON_JC30501 ;
INSERT INTO LARSON_DEV.LARSON_RAW.RTSAL_LARSON_JC30501 SELECT * FROM LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_JC30501 ;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_JC30501 ;