TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTSAL_LARSON_JC01701 ;
INSERT INTO LARSON_DEV.LARSON_RAW.RTSAL_LARSON_JC01701 select * from LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_JC01701 ;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_JC01701 ;