TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMPT;
INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMPT SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMPT;
TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMPT;