TRUNCATE TABLE CROMPCO_DEV.CROMPCO_RAW.RTSAL_INVOICE;
INSERT INTO CROMPCO_DEV.CROMPCO_RAW.RTSAL_INVOICE SELECT * FROM CROMPCO_DEV.CROMPCO_STAGE.STSAL_INVOICE;
TRUNCATE TABLE CROMPCO_DEV.CROMPCO_STAGE.STSAL_INVOICE;