TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMEMPL;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMEMPL SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMEMPL;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMEMPL;