TRUNCATE TABLE LARSON_DEV.BKL_RAW.RTSAL_BKL_SOP30200 ;
INSERT INTO LARSON_DEV.BKL_RAW.RTSAL_BKL_SOP30200 SELECT * FROM LARSON_DEV.BKL_STAGE.STGSAL_BKL_SOP30200 ;
TRUNCATE TABLE LARSON_DEV.BKL_STAGE.STGSAL_BKL_SOP30200 ;