TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMPTEQ;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOVMPTEQ SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMPTEQ;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOVMPTEQ;