TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOGLACGRP;
INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOGLACGRP SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOGLACGRP;
TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOGLACGRP;