TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_GL00100 ;
INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_GL00100 select * from LARSON_DEV.NMA_STAGE.STGSAL_NMA_GL00100 ;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_GL00100 ;