TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTSAL_LARSON_SOP30200 ;
INSERT INTO LARSON_DEV.LARSON_RAW.RTSAL_LARSON_SOP30200 SELECT * FROM LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_SOP30200 ;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_SOP30200 ;