TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOARCUS;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOARCUS SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOARCUS;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOARCUS;