TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOARIBH;

INSERT INTO WILDCO_DEV.PESDAT_RAW.RTSAL_WILDCOARIBH SELECT * FROM WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOARIBH;

TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGSAL_WILDCOARIBH;