TRUNCATE TABLE LARSON_DEV.NMA_RAW.RTSAL_NMA_ZZZ51_SLPRSNID;
INSERT INTO LARSON_DEV.NMA_RAW.RTSAL_NMA_ZZZ51_SLPRSNID select * from LARSON_DEV.NMA_STAGE.STGSAL_NMA_ZZZ51_SLPRSNID ;
TRUNCATE TABLE LARSON_DEV.NMA_STAGE.STGSAL_NMA_ZZZ51_SLPRSNID ;