TRUNCATE TABLE LARSON_DEV.LARSON_RAW.RTSAL_LARSON_JC40303 ;
INSERT INTO LARSON_DEV.LARSON_RAW.RTSAL_LARSON_JC40303 select * from LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_JC40303 ;
TRUNCATE TABLE LARSON_DEV.LARSON_STAGE.STGSAL_LARSON_JC40303 ;