TRUNCATE TABLE WILDCO_DEV.PESDAT_RAW.RTFIN_WILDCOGLAMF ;
INSERT INTO WILDCO_DEV.PESDAT_RAW.RTFIN_WILDCOGLAMF select * from WILDCO_DEV.PESDAT_STAGE.STGFIN_WILDCOGLAMF ;
TRUNCATE TABLE WILDCO_DEV.PESDAT_STAGE.STGFIN_WILDCOGLAMF ;