truncate table WILDCO_DEV.PESDAT_RAW.RTFIN_WILDCOCSFSC;

insert into WILDCO_DEV.PESDAT_RAW.RTFIN_WILDCOCSFSC select * from WILDCO_DEV.PESDAT_STAGE.STGFIN_WILDCOCSFSC;

truncate table WILDCO_DEV.PESDAT_STAGE.STGFIN_WILDCOCSFSC;